# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\ClientExport\DataSources\JsonServiceClientDataSource:
        class: 'App\ClientExport\DataSources\JsonServiceClientDataSource'

    App\ClientExport\DataSources\XMLClientDataSource:
        class: 'App\ClientExport\DataSources\XMLClientDataSource'
        arguments: ['%kernel.project_dir%']

    App\ClientExport\Strategy\CsvClientExportStrategy:
        class: 'App\ClientExport\Strategy\CsvClientExportStrategy'
        arguments: ['%kernel.project_dir%']

    App\ClientExport\ClientsExportService:
        class: 'App\ClientExport\ClientsExportService'
        arguments:
            - ['@App\ClientExport\DataSources\JsonServiceClientDataSource', '@App\ClientExport\DataSources\XMLClientDataSource']
            - '@App\ClientExport\Strategy\CsvClientExportStrategy'

    App\ClientExport\Command:
        class: 'App\ClientExport\Command'
        arguments:
            - '@App\ClientExport\ClientsExportService'
